[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "ipykernel-helper"
dynamic = ["version"]
description = "Helpers for ipykernel and friends"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "Apache-2.0"}
authors = [{name = "Jeremy Howard", email = "info@fast.ai"}]
keywords = ['nbdev', 'jupyter', 'notebook', 'python']
classifiers = ["Natural Language :: English", "Intended Audience :: Developers", "Development Status :: 3 - Alpha", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3 :: Only"]
dependencies = ['python-fasthtml', 'fastcore>=1.12.28', 'toolslm>=0.3.13', 'jedi', 'ipython', 'ipykernel', 'beautifulsoup4', 'lxml', 'html2text', 'cloudscraper', 'ghapi']

[project.urls]
Repository = "https://github.com/AnswerDotAI/ipykernel-helper"
Documentation = "https://AnswerDotAI.github.io/ipykernel-helper"

[project.entry-points.nbdev]
ipykernel_helper = "ipykernel_helper._modidx:d"

[tool.setuptools.dynamic]
version = {attr = "ipykernel_helper.__version__"}

[tool.setuptools.packages.find]
include = ["ipykernel_helper"]

[tool.nbdev]
allowed_cell_metadata_keys = ["solveit_ai"]
custom_sidebar = false
