# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ipykernel-helper',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/ipykernel-helper',
                'lib_path': 'ipykernel_helper'},
  'syms': {'ipykernel_helper.core': {'ipykernel_helper.core.foo': ('core.html#foo', 'ipykernel_helper/core.py')}}}
