"""API for ipykernel-helper

Docs: https://AnswerDotAI.github.io/ipykernel-helper/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['prose_types', 'transient', 'run_cmd', 'get_md', 'scrape_url', 'read_url', 'fix_editable_priority', 'call_tool',
           'info_md', 'load_ipython_extension']

# %% ../nbs/00_core.ipynb #9470a755
from fasthtml.common import *
from pyskills import resolve
from fastcore.meta import delegates
from fastcore.utils import patch,patch_to
from fastcore.docments import sig_source,DocmentText
from fastcore.net import HTTP404NotFoundError
from fastcore.xtras import truncstr
from fastcore.aio import maybe_await,enable_async_magics
from types import ModuleType, FunctionType, MethodType, BuiltinFunctionType
from functools import cmp_to_key,partial
from textwrap import dedent
from fastcore.funccall import *
import ipyfuncs
from urllib.parse import urlparse, urljoin

import re,os,html2text,base64,inspect

from IPython.core.interactiveshell import InteractiveShell

from IPython.core.display import DisplayObject
from IPython.display import display,Markdown,HTML
from IPython.core.oinspect import Inspector
from IPython.core.displayhook import DisplayHook
from ipykernel.displayhook import ZMQShellDisplayHook
from IPython.core.formatters import DisplayFormatter

# %% ../nbs/00_core.ipynb #281193c9
@patch
def xpush(self:InteractiveShell, interactive=False, **kw):
    "Like `push`, but with kwargs"
    self.push(kw, interactive=interactive)

# %% ../nbs/00_core.ipynb #bb1ed4d6
def transient(data='', subtype='plain', mimetype='text', meta=None, update=False, **kw):
    display({f'{mimetype}/{subtype}': data}, raw=True, metadata=meta, transient=kw, update=update)

# %% ../nbs/00_core.ipynb #0e32b2c6
def run_cmd(cmd, data='', meta=None, update=False, **kw):
    transient(data, meta=meta, update=update, cmd=cmd, **kw)

# %% ../nbs/00_core.ipynb #0f2092d8
def _absolutify_imgs(md, base_url):
    def fix(m):
        alt,img_url = m.group(1),m.group(2)
        if not img_url.startswith('http'): img_url = urljoin(base_url, img_url)
        alt = alt.replace('\\','')
        return f'![{alt}]({img_url})'
    return re.sub(r'!\[(.*?)\]\((.*?)\)', fix, md)

# %% ../nbs/00_core.ipynb #b148c51d
def get_md(html, url='', mmode=None, ignore_links=False, ignore_images=False, mark_code=True):
    "Convert HTML to markdown with absolute image URLs and optional math mode"
    h = html2text.HTML2Text()
    h.body_width = 0
    h.ignore_links, h.ignore_images, h.mark_code = ignore_links, ignore_images, mark_code
    res = _absolutify_imgs(h.handle(str(html)), url)
    if mmode == 'safe': res = res.replace(r'\\(',r'\(').replace(r'\\)',r'\)')
    return re.sub(r'\[code]\s*\n(.*?)\n\[/code]', lambda m: f'````\n{dedent(m.group(1))}\n````', res, flags=re.DOTALL).strip()

# %% ../nbs/00_core.ipynb #18980edf
def scrape_url(url): 
    from cloudscraper import create_scraper
    o = create_scraper().get(url)
    if not o.encoding or o.encoding == 'ISO-8859-1': o.encoding = 'utf-8'
    return o

# %% ../nbs/00_core.ipynb #cc5804a5
def _get_math_mode():
    v = os.getenv('USE_KATEX', '')
    if v.lower() in {'0', 'false', 'none', ''}: return None
    return 'dollar' if v.lower().startswith('d') else 'safe'

# %% ../nbs/00_core.ipynb #619fe2a4
def _aify_imgs(md): return re.sub(r'!\[(.*?)\]\((.*?)\)', r'![\1](\2#ai)', md)

# %% ../nbs/00_core.ipynb #9a126dad
def _extract_section(soup, url, selector=None):
    "Extract a specific section from soup, or the whole thing"
    if selector: return '\n\n'.join(str(s) for s in soup.select(selector))
    parsed = urlparse(url)
    if not parsed.fragment: return str(soup)
    section = soup.find(id=parsed.fragment)
    if not section: return ''
    elements = [section]
    current = section.next_sibling
    while current:
        if hasattr(current, 'name') and current.name == section.name: break
        elements.append(current)
        current = current.next_sibling
    return ''.join(str(el) for el in elements)

# %% ../nbs/00_core.ipynb #6d6bb188
def _convert_math(soup, mode):
    for math in soup.find_all('math'):
        annot = math.find('annotation', {'encoding': 'application/x-tex'})
        if not annot: continue
        tex,display = annot.text.strip(), math.get('display') == 'block'
        if mode == 'dollar': wrap = f'$${tex}$$' if display else f'${tex}$'
        else: wrap = f'$${tex}$$' if display else fr'\({tex}\)'
        math.replace_with(wrap)

# %% ../nbs/00_core.ipynb #d5c677e7
def read_url(
    url:str, # URL to read
    as_md:bool=True, # Convert HTML to markdown
    extract_section:bool=True, # Extract section matching URL fragment or selector
    selector:str=None, # CSS selector to extract specific content
    ai_img:bool=False # Add #ai suffix to image URLs
):
    "Read url from web"
    from bs4 import BeautifulSoup
    o = scrape_url(url)
    ctype = (o.headers.get('content-type') or 'text/plain').split(';')[0]
    res = o.text
    if ctype == 'text/html':
        soup = BeautifulSoup(res, 'lxml')
        if ('#' in url and extract_section) or selector: soup = BeautifulSoup(_extract_section(soup, url, selector), 'lxml')
        mmode = _get_math_mode()
        if mmode: _convert_math(soup, mmode)
        base = soup.find('base')
        base_url = urljoin(url, base['href'] if base else '')
        res = get_md(soup, base_url, mmode) if as_md else str(soup)
    if ai_img: res = _aify_imgs(res)
    return res

# %% ../nbs/00_core.ipynb #dd0a0b71
def fix_editable_priority():
    import sys
    from importlib.machinery import PathFinder
    try: sys.meta_path.append(sys.meta_path.pop(sys.meta_path.index(PathFinder)))
    except ValueError: pass

# %% ../nbs/00_core.ipynb #6d5eebf0
prose_types = { 'pandas.DataFrame', 'pandas.io.formats.style.Styler',
    'polars.dataframe.frame.DataFrame', 'polars.series.series.Series' }

def _type_mros(o): return [f'{c.__module__}.{c.__qualname__}' for c in type(o).__mro__]
def _is_prose(o): return any(isinstance(o, t) if isinstance(t, type) else t in _type_mros(o) for t in prose_types)

@patch
def format(self:DisplayFormatter, obj, include=None, exclude=None):
    data,meta = self._orig_format(obj, include=include, exclude=exclude)
    if 'text/html' in data and _is_prose(obj): meta.setdefault('text/html', {})['prose'] = True
    return data,meta


# %% ../nbs/00_core.ipynb #10d99f58
from IPython.display import TextDisplayObject,DisplayObject
from pathlib import PurePath

# %% ../nbs/00_core.ipynb #a758340e
@patch
def __repr__(self:DisplayObject):
    s = self.data or self.url or self.filename
    if s is None: return None
    if not isinstance(s, str): s = truncstr(str(s), 30)
    return f"{type(self).__name__}({s})"

# %% ../nbs/00_core.ipynb #5a6b8ed2
@patch
def __init__(self:TextDisplayObject, data=None, url=None, filename=None, metadata=None):
    "Like `DisplayObject.__init__`, but never auto-detects `data` as a URL/filename"
    if isinstance(data, (Path, PurePath)): data = str(data)
    self.url, self.filename, self.data = url, filename, data
    if metadata is not None: self.metadata = metadata
    elif self.metadata is None: self.metadata = {}
    self.reload()
    self._check_data()

# %% ../nbs/00_core.ipynb #b671332c
async def call_tool(func, kw):
    "Call `func(**kw)` with `coerce_inputs`"
    return await maybe_await(func(**coerce_inputs(func, kw)))

# %% ../nbs/00_core.ipynb #3c6948a7
def _lineno(obj):
    "Source line number of `obj`, or `None` if unavailable"
    try: return inspect.getsourcelines(obj)[1]
    except (TypeError, OSError): return None

def _src_target(obj):
    "Object whose file/source best represents `obj`: unwrap wrappers, properties, and partials; instances resolve to their type"
    if not hasattr(obj, '__signature__'): obj = getattr(obj, '__wrapped__', obj)
    obj = getattr(obj, 'fget', None) or getattr(obj, 'fset', None) or obj
    if isinstance(obj, partial): obj = obj.func
    if isinstance(obj, (type, ModuleType, FunctionType, MethodType, BuiltinFunctionType)): return obj
    return type(obj)

# %% ../nbs/00_core.ipynb #cf893c28
@patch
def _get_info(self:Inspector, obj, oname='', formatter=None, info=None, detail_level=0, omit_sections=()):
    "Custom formatter for ? and ?? output"
    orig = self._orig__get_info(obj, oname=oname, formatter=formatter, info=info,
                                detail_level=detail_level, omit_sections=omit_sections)
    try:
        tgt = _src_target(obj)
        oinfo = self.info(obj, oname=oname, info=info, detail_level=0)
        src = self.info(tgt, detail_level=2).get('source') if detail_level else None
        out = [f"````python\n{dedent(src) if src else DocmentText(obj)}\n````"]
        if not detail_level and tgt is type(obj) and (c:=oinfo.get('string_form')):
            out.append(f"**String form:** `{truncstr(c.splitlines()[0], 100)}`")
        finfo = oinfo if tgt is obj else self.info(tgt)
        if c:=finfo.get('file'):
            ln = _lineno(tgt)
            out.append(f"**File:** `{c}`" + (f"; line: {ln}" if ln else ""))
        if not detail_level and (c:=oinfo.get('type_name')): out.append(f"**Type:** {c}")
        return {'text/markdown': '\n\n'.join(out), 'text/html': '', 'text/plain': orig['text/plain']}
    except Exception: return orig

# %% ../nbs/00_core.ipynb #e0e6d147
def info_md(
    obj:str|object, # Object to get info for, or its name
    source:bool=False
):
    "With `source=False` same as ipython's `?`, otherwise same as `??`"
    obj = resolve(obj)
    r = get_ipython().inspector._get_info(obj, '', detail_level=1 if source else 0)
    return PrettyString(r.get('text/markdown') or re.sub(r'\x1b\[[0-9;]*m', '', r['text/plain']))

# %% ../nbs/00_core.ipynb #290963a0
from IPython.core.ultratb import SyntaxTB

# %% ../nbs/00_core.ipynb #eaa7a5e8
@patch()
def structured_traceback(self:SyntaxTB, etype, evalue, etb, tb_offset=None, context=5):
    if hasattr(evalue, 'msg') and not isinstance(evalue.msg, str): evalue.msg = str(evalue.msg)
    return self._orig_structured_traceback(etype, evalue, etb, tb_offset=tb_offset, context=context)

# %% ../nbs/00_core.ipynb #33cb1440
@patch_to(inspect, nm="getfile")
def _getfile(obj): return str(inspect._orig_getfile(obj))

# %% ../nbs/00_core.ipynb #ff4984b9
def _fmt_magic_res(result): return HTML(to_xml(result)) if isinstance(result, FT) else result

def load_ipython_extension(ip):
    ns = ip.user_ns
    for o in ('transient','run_cmd','maybe_await','call_tool'): ns[o] = globals()[o]
    enable_async_magics(ip, fmt=_fmt_magic_res)  # magics (line and cell) may be async; FT results become HTML

    @patch_to(type(ip.displayhook))
    def compute_format_data(self, result):
        format_dict, md_dict = self._orig_compute_format_data(result)
        md_dict['__type'] = type(result).__qualname__
        return format_dict, md_dict
